### ISSUE TITLE
Bad request when trying to login

### ISSUE THREAD

**Issue by capaldo** [ayntgl/discordo#104]
I'm getting the following error when i run the application:

Any idea as to what may be causing it?

```
panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"} [recovered]
	panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"}

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0x140001f4000)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/application.go:243 +0x64
panic({0x10495bc20, 0x14000886000})
	runtime/panic.go:1038 +0x21c
main.onLoginFormLoginButtonSelected()
	github.com/ayntgl/discordo/main.go:116 +0x444
github.com/rivo/tview.(*Button).InputHandler.func1(0x140005b6780, 0x140001f05d0)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/button.go:129 +0x58
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0x140005b6780, 0x140001f05d0)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/box.go:161 +0x70
github.com/rivo/tview.(*Form).InputHandler.func1(0x140005b6780, 0x140001f05d0)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/form.go:673 +0xb0
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0x140005b6780, 0x140001f05d0)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/box.go:161 +0x70
github.com/rivo/tview.(*Application).Run(0x140001f4000)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/application.go:335 +0x858
main.main()
	github.com/ayntgl/discordo/main.go:100 +0xeb4
```

**Comment by ayntgl** [comment]
[#86](https://github.com/ayntgl/discordo/issues/86#issuecomment-954091787). If you need further assistance, join the [official Discord guild](https://discord.gg/u49vegcfnh).
