### ISSUE TITLE
2FA breaking login

### ISSUE THREAD

**Issue by Just-Danuse** [ayntgl/discordo#110]
I have enabled 2FA and when i try to enter 2FA code, only new login button and field "code" appear, the last button will crash discordo with this error:

```panic: HTTP 400 Bad Request, {"message": "Invalid two-factor code", "code": 60008} [recovered]
        panic: HTTP 400 Bad Request, {"message": "Invalid two-factor code", "code": 60008}

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        /home/daniel/go/pkg/mod/github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/application.go:243 +0x4d panic({0x7502c0, 0xc00058e420})
        /usr/lib/go/src/runtime/panic.go:1038 +0x215
github.com/ayntgl/discordo/ui.OnLoginFormLoginButtonSelected.func1()
        /home/daniel/discordo/ui/handlers.go:337 +0x231
github.com/rivo/tview.(*Button).InputHandler.func1(0xc0001b1d38, 0x6f441f)
        /home/daniel/go/pkg/mod/github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/button.go:129 +0x42
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0002fa3c0, 0xc0003e0dc8)
        /home/daniel/go/pkg/mod/github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/box.go:161 +0x53
github.com/rivo/tview.(*Form).InputHandler.func1(0x40e9c7, 0x10)
        /home/daniel/go/pkg/mod/github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/form.go:673 +0xb7
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0001bc000, 0xc0001b1e58)
        /home/daniel/go/pkg/mod/github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/box.go:161 +0x53
github.com/rivo/tview.(*Application).Run(0xc0001ba000)
        /home/daniel/go/pkg/mod/github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/application.go:335 +0x886
main.main()
        /home/daniel/discordo/main.go:36 +0x15f```

![2FA login](https://user-images.githubusercontent.com/45514518/148760097-81f8da08-2f24-4639-bdd6-2ec057a94867.png)

**Comment by Just-Danuse** [comment]
#86 i know

**Comment by ayntgl** [comment]
@Just-Danuse, the new Discordo rewrite does not support the `token` field in the configuration file for security reasons. Instead, you can set the environment variable `DISCORDO_TOKEN` to login (eg: `DISCORDO_TOKEN="TOKEN_HERE" discordo`).

**Comment by Just-Danuse** [comment]
It is working now, thanks
